- name: copying {{component}} repo
  ansible.builtin.copy:
   src: mongodb.repo
   dest: /etc/yum.repos.d/mongodb.repo

- name: install {{component}}
  ansible.builtin.package:
   name: mongodb-org
   state: present

- name: update {{component}} visibility
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: starting {{component}} service
  systemd:
   name: mongod
   state: started
   enabled: yes

- name: downloading the schema
  ansible.builtin.unarchive:
   src: https://github.com/stans-robot-project/mongodb/archive/main.zip
   dest: /tmp
   remote_src: yes

- name: injecting the schema
  community.mongodb.mongodb_shell:
   file: "/tmp/mongodb-main/{{item}}.js"
   idempotent: yes
  loop:
   - users
   - catalogue

