- name: installin maven
  ansible.builtin.package:
   name: maven
   state: present

- name: add service user account
  ansible.builtin.user:
   name: "{{appuser}}"
   comment: adding account - {{appuser}}

- name: cleanup of "{{appuser}}" dir
  ansible.builtin.files:
   path: /home/{{appuser}}/{{component}}
   state: absent

- name: downloading {{component}} repo
  ansible.builtin.unarchive:
   src: https://github.com/stans-robot-project/{{component}}/archive/main.zip
   dest: /tmp
   remote_src: yes
  
- name: copying the files to {{appuser}}
  ansible.builtin.copy:
   src: /tmp/{{component}}-main/
   dest: /home/{{appuser}}/{{component}}
   owner: "{{appuser}}"
   group: "{{appuser}}"
   remote_src: yes

- name: performing maven cleanup
  ansible.builtin.shell: mvn clean package && mv target/{{component}}-1.0.jar {{component}}.jar
  args:
   chdir: /home/{{appuser}}/{{component}}/

- name: copying the systemd file to {{component}} server
  ansible.builtin.copy:
   src: systemd.service
   dest: /etc/systemd/system/shipping.service

- name: starting {{component}} service
  systemd:
   name: "{{component}}"
   state: restarted
   enabled: yes