- name: privilage access
  hosts: all
  become: yes
  tasks: 
   - name: get the user id
     ansible.builtin.shell: id
     register: OUT

   - name: print user id
     ansible.builtin.debug:
      msg: "{{OUT}}"
    