- name: dealing with packages
  hosts: all
  become: yes
  tasks:
   - name: install nginx
     ansible.builtin.package:
      name: nginx
      state: present

   - name: update nginx
     ansible.builtin.package:
      name: nginx
      state: latest
      