# - name: configuring nodejs for {{component}}
#   ansible.builtin.shell: yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y

- name: installing nodejs
  ansible.builtin.package:
   name: nodejs
   state: present

- name: adding service account {{appuser}}
  ansible.builtin.user:
   name: "{{appuser}}"
   comment: adding service account

- name: cleaning up the {{appuser}}
  ansible.builtin.file:
   path: /home/{{appuser}}/{{component}}
   state: absent
  ignore_errors: yes

- name: create app directory
  ansible.builtin.file:
   path: /home/{{appuser}}/{{component}}/
   state: directory
   mode: '0755'
  become_user: "{{appuser}}"
 
- name: download the repo
  ansible.builtin.unarchive:
   src: http://172.31.25.180:8081/repository/{{component}}/{{component}}-{{APP_VERSION}}.zip
   dest: /home/{{appuser}}/{{component}}/
   remote_src: yes

# - name: downloading the schema
#   ansible.builtin.unarchive:
#    src: https://github.com/stans-robot-project/user/archive/main.zip
#    dest: /tmp
#    remote_src: yes

# - name: cleaning up the {{appuser}}
#   ansible.builtin.file:
#    path: /home/{{appuser}}/{{component}}
#    state: absent
#   ignore_errors: yes

# - name: copying to {{appuser}}
#   ansible.builtin.copy:
#    src: /tmp/{{component}}-main/
#    dest: /home/{{appuser}}/{{component}}
#    owner: "{{appuser}}"
#    group: "{{appuser}}"
#    remote_src: yes

# - name: installing npm
#   npm:
#    path: /home/{{appuser}}/{{component}}

- name: copying the systemd file to {{appuser}}
  ansible.builtin.template:
   src: systemd.service
   dest: /etc/systemd/system/{{component}}.service

- name: starting {{component}} service
  systemd:
   name: "{{component}}"
   state: restarted
   enabled: yes

- name: Installing Filebeat 
  ansible.builtin.include_role:
   name: elk
   tasks_from: filebeat

- name: set hostname
  ansible.builtin.shell: set-hostname {{component}}-{{env}}


  
