- name: install python
  ansible.builtin.package:
   name: 
    - python36 
    - gcc 
    - python3-devel
   state: present

- name: add {{appuser}} account 
  ansible.builtin.user: 
   user: "{{appuser}}"
   comment: adding service account
  register: out

- name: print user out
  ansible.builtin.debug:
   msg: output of adding a user is {{out}}

- name: print user and group id
  ansible.builtin.debug:
   msg: value of userid is {{user_id}} and group id is {{group_id}}

- name: download {{component}} repo
  ansible.builtin.unarchive:
   src: https://github.com/stans-robot-project/payment/archive/main.zip
   dest: /tmp
   remote_src: yes

- name: perform cleanup 
  ansible.builtin.file:
   path: /home/{{appuser}}/{{component}}
   state: absent

- name: copying to {{appuser}} account
  ansible.builtin.copy: 
   src: /tmp/{{component}}-main/
   dest: /home/{{appuser}}/{{component}}
   owner: "{{appuser}}"
   group: "{{appuser}}"
   remote_src: yes

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: /home/{{appuser}}/{{component}}/requirements.txt
    executable: pip3
   
- name: update userid
  ansible.builtin.lineinfile:
    path: /home/{{appuser}}/{{component}}/{{component}}.ini
    regexp: 'uid'
    line: uid = {{out.uid}}

- name: update groupid
  ansible.builtin.lineinfile:
    path: /home/{{appuser}}/{{component}}/{{component}}.ini
    regexp: 'gid'
    line: gid = {{out.group}}

- name: updating systemd file
  ansible.builtin.template:
   src: systemd.service
   dest: /etc/systemd/system/payment.service

- name: starting {{component}} service
  systemd:
   name: "{{component}}"
   state: restarted
   enabled: yes

