- name: download erlang repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | sudo bash

- name: download {{component}} repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | sudo bash

- name: install {{component}} 
  ansible.builtin.package: 
   name: rabbitmq-server
   state: present
  
- name: starting {{component}} service
  systemd:
   name: rabbitmq-server
   state: started
   enabled: yes

- name: adding {{component}} user account
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    tags: administrator
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present

- name: set hostname for {{component}} server
  ansible.builtin.shell: set-hostname {{component}}-{{env}}
