- name: copying logstash config
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf

- name: restarting logstash
  systemd: 
   name: logstash
   state: restarted
   enabled: yes
   daemon-reload: yes

- name: Waiting for logstah port to be in listening state 
  ansible.builtin.wait_for:
    port: 5044 
    delay: 30 
    timeout: 60