- name: configuring {{component}} repo
  ansible.builtin.shell: yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y
  ignore_errors: yes

- name: install nodejs
  ansible.builtin.package:
   name: nodejs
   state: present
     
- name: adding user account {{appuser}}
  ansible.builtin.user:
   name: "{{appuser}}"
   comment: adding {{appuser}} service user

- name: cleaning up the {{appuser}}
  ansible.builtin.file:
   path: /home/{{appuser}}/{{component}}
   state: absent
  ignore_errors: yes

- name: create app directory
  ansible.builtin.file:
   path: /home/{{appuser}}/{{component}}/
   state: directory
   mode: '0755'
  become_user: "{{appuser}}"
 
- name: download the repo
  ansible.builtin.get_url:
   url: http://172.31.25.180:8081/repository/{{component}}/{{component}}-{{APP_VERSION}}.zip
   dest: /home/{{appuser}}/{{component}}/
   url_username: admin
   url_password: password
  remote_src: yes

# - name: extracting files into {{appuser}}
#   ansible.builtin.copy:
#    src: /tmp/catalogue-main/
#    dest: /home/{{appuser}}/{{component}}
#    owner: "{{appuser}}"
#    group: "{{appuser}}"
#    remote_src: yes
  
# - name: performing npm install
#   npm:
#    path: /home/{{appuser}}/{{component}}

- name: copying systemd file
  ansible.builtin.template:
   src: systemd.service
   dest: /etc/systemd/system/{{component}}.service
  
- name: starting {{component}} service
  systemd:
   name: "{{component}}"
   state: restarted
   enabled: yes
   daemon_reload: yes

- name: Installing Filebeat 
  ansible.builtin.include_role:
   name: elk
   tasks_from: filebeat

- name: Installing rsyslog
  ansible.builtin.include_role:
   name: elk
   tasks_from: rsyslog.yml

- name: set server name
  ansible.builtin.shell: set-hostname {{component}}-{{env}}


 

