# - name: configuring {{component}} repo
#   ansible.builtin.shell: yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y

- name: install nodejs
  ansible.builtin.package:
   name: nodejs
   state: present
     
- name: adding user account {{appuser}}
  ansible.builtin.user:
   name: "{{appuser}}"
   comment: adding {{appuser}} service user
 
- name: download the repo
  ansible.builtin.unarchive:
   src: https://github.com/stans-robot-project/catalogue/archive/main.zip
   dest: /tmp
   remote_src: yes

- name: performing cleanup 
  ansible.builtin.file: 
   path: /home/{{appuser}}/{{component}}
   state: absent
  ignore_errors: yes

- name: extracting files into {{appuser}}
  ansible.builtin.copy:
   src: /tmp/catalogue-main/
   dest: /home/{{appuser}}/{{component}}
   owner: "{{appuser}}"
   group: "{{appuser}}"
   remote_src: yes
  
- name: performing npm install
  npm:
   path: /home/{{appuser}}/{{component}}

- name: copying systemd file
  ansible.builtin.template:
   src: systemd.service
   dest: /etc/systemd/system/{{component}}.service
  
- name: starting {{component}} service
  systemd:
   name: "{{component}}"
   state: restarted
   enabled: yes
   daemon_relaod: yes

- name: set server name
  ansible.builtin.shell: set-hostname {{component}}-{{env}}


 

