- name: download the repo
  ansible.builtin.unarchive:
   src: https://github.com/stans-robot-project/{{component}}/archive/main.zip
   dest: /tmp
   remote_src: yes
  ignore_errors: yes

- name: performing cleanup 
  ansible.builtin.file: 
   path: /home/{{appuser}}/{{component}}
   state: absent
  ignore_errors: yes

- name: extracting files into {{appuser}}
  ansible.builtin.copy:
   src: /tmp/{{component}}-main/
   dest: /home/{{appuser}}/{{component}}
   owner: "{{appuser}}"
   group: "{{appuser}}"
   remote_src: yes
  ignore_errors: yes